export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_TOP_ARTISTS: "SET_TOP_ARTISTS",
    SET_TOP_LIKED: "SET_TOP_LIKED",
    SET_TOP_SONGS: "SET_TOP_SONGS",
    SET_USER_AUTH: "SET_USER_AUTH",
};